sudo: required

services:
  - docker

before_install:
  - docker build -t owned/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run owned/react-test npm run test -- --coverage

after_success:
  - docker build -t owned/multi-client ./client
  - docker build -t owned/multi-nginx ./nginx
  - docker build -t owned/multi-worker ./worker
  - docker build -t owned/multi-server ./server

## LOGIN DOCKER CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

## PUSH DOCKER HUB
- docker push owned/multi-client
- docker push owned/multi-nginx
- docker push owned/multi-worker
- docker push owned/multi-server
